/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const { getSidebarIndex } = require("./docs/theindex");

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docsSidebar: [
    {type: 'doc', id: 'README', label: '首页'},
    ...getSidebarIndex().map(cat => (
      {
        type: 'category',
        label: cat.title,
        collapsed: true,
        collapsible: true,
        items: [
          { type: 'autogenerated', dirName: '' + cat.folder }
        ],
      }
    ))
  ]
};

module.exports = sidebars;
