/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const { getSidebarIndex } = require("./docs/theindex");

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docsSidebar: [
    { type: 'doc', id: 'README', label: '首页' },
    //@ts-ignore
    ...getSidebarIndex().map(cat => (
      {
        type: 'category',
        label: cat.title,
        collapsed: true,
        collapsible: true,
        items: [
          { type: 'autogenerated', dirName: cat.folder }
        ],
      }
    )),
    //@ts-ignore
    { type: 'ref', id: 'unlimited-paper-works/index', label: '魔法部日志（又名论文阅读日志）' },
  ],
  upwSidebar: [
    { type: 'ref', id: 'README', label: '工具箱的深度学习记事簿' },
    {
      type: 'category',
      label: '魔法部日志（又名论文阅读日志）',
      collapsed: false,
      collapsible: false,
      items: [
        { type: 'autogenerated', dirName: 'unlimited-paper-works' }
      ],
    }
  ],
  playgroundSidebar: [
    {
      type: 'category',
      label: 'Playground',
      collapsed: false,
      collapsible: false,
      items: [
        { type: 'autogenerated', dirName: 'playground' }
      ],
    }
  ],
};

module.exports = sidebars;
